CREATE TABLE CLIENT(
    CODE NUMBER(4),
    NOM VARCHAR(30) NOT NULL,
    PRENOM VARCHAR(30) NOT NULL,
    DDN DATE NOT NULL,
    AD VARCHAR(30) NOT NULL,
    TEL NUMBER(10) NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE CLASSE(
    NOM VARCHAR(30),
    PRIMARY KEY (NOM)
);

CREATE TABLE ESPECE(
    NOM VARCHAR(30),
    CLASSE VARCHAR(30),
    FOREIGN KEY (CLASSE) REFERENCES CLASSE(NOM),
    PRIMARY KEY (NOM)
);

CREATE TABLE ANIMAL(
    CODE NUMBER(4),
    NOM VARCHAR(30) NOT NULL,
    POIDS FLOAT NOT NULL,
    TAILLE FLOAT NOT NULL,
    NAISSANCE DATE NOT NULL,
    ESPECE VARCHAR(30),
    CLIENT NUMBER(4),
    TRAITEMENT XMLTYPE NOT NULL,
    FOREIGN KEY (ESPECE) REFERENCES ESPECE(NOM),
    FOREIGN KEY (CLIENT) REFERENCES CLIENT(CODE),
    CHECK ((POIDS>0) and (TAILLE>0)),
    PRIMARY KEY (CODE)
);
