DROP TABLE MEDI_TRAITEMENT;
DROP TABLE MEDI_CORESPOND_ANI;
DROP TABLE MEDICAMENT;
DROP TABLE TRAITEMENT;
DROP TABLE VETERINAIRE;
DROP TABLE ASSISTANT;
DROP TABLE ANIMAL;
DROP TABLE ESPECE;
DROP TABLE CLASSE;
DROP TABLE CLIENTS;

DROP TYPE TMEDICAMENT;
DROP TYPE TTRAITEMENT;
DROP TYPE TANIMAL;
DROP TYPE TEMPLOYE;
DROP TYPE TESPECE;
DROP TYPE TCLASSE;
DROP TYPE PERSONNE;